services:
  - type: web
    name: jobs-api
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_LIFETIME
        sync: false
